// kbeauty.market 지원 국가 및 아마존 마켓플레이스 설정

export const SUPPORTED_COUNTRIES = {
  US: {
    name: '미국',
    nameEn: 'United States',
    code: 'US',
    currency: 'USD',
    flag: '🇺🇸',
    amazon: {
      domain: 'amazon.com',
      apiEndpoint: 'https://webservices.amazon.com/paapi5/getitems',
      region: 'us-east-1',
      marketplace: 'ATVPDKIKX0DER',
    },
    language: 'en-US',
    timezone: 'America/New_York',
    shippingZone: 'americas',
  },
  JP: {
    name: '일본',
    nameEn: 'Japan',
    code: 'JP',
    currency: 'JPY',
    flag: '🇯🇵',
    amazon: {
      domain: 'amazon.co.jp',
      apiEndpoint: 'https://webservices.amazon.co.jp/paapi5/getitems',
      region: 'us-west-2',
      marketplace: 'A1VC38T7YXB528',
    },
    language: 'ja-JP',
    timezone: 'Asia/Tokyo',
    shippingZone: 'asia',
  },
  DE: {
    name: '독일',
    nameEn: 'Germany',
    code: 'DE',
    currency: 'EUR',
    flag: '🇩🇪',
    amazon: {
      domain: 'amazon.de',
      apiEndpoint: 'https://webservices.amazon.de/paapi5/getitems',
      region: 'eu-west-1',
      marketplace: 'A1PA6795UKMFR9',
    },
    language: 'de-DE',
    timezone: 'Europe/Berlin',
    shippingZone: 'europe',
  },
  GB: {
    name: '영국',
    nameEn: 'United Kingdom',
    code: 'GB',
    currency: 'GBP',
    flag: '🇬🇧',
    amazon: {
      domain: 'amazon.co.uk',
      apiEndpoint: 'https://webservices.amazon.co.uk/paapi5/getitems',
      region: 'eu-west-1',
      marketplace: 'A1F83G8C2ARO7P',
    },
    language: 'en-GB',
    timezone: 'Europe/London',
    shippingZone: 'europe',
  },
  FR: {
    name: '프랑스',
    nameEn: 'France',
    code: 'FR',
    currency: 'EUR',
    flag: '🇫🇷',
    amazon: {
      domain: 'amazon.fr',
      apiEndpoint: 'https://webservices.amazon.fr/paapi5/getitems',
      region: 'eu-west-1',
      marketplace: 'A13V1IB3VIYZZH',
    },
    language: 'fr-FR',
    timezone: 'Europe/Paris',
    shippingZone: 'europe',
  },
  IT: {
    name: '이탈리아',
    nameEn: 'Italy',
    code: 'IT',
    currency: 'EUR',
    flag: '🇮🇹',
    amazon: {
      domain: 'amazon.it',
      apiEndpoint: 'https://webservices.amazon.it/paapi5/getitems',
      region: 'eu-west-1',
      marketplace: 'APJ6JRA9NG5V4',
    },
    language: 'it-IT',
    timezone: 'Europe/Rome',
    shippingZone: 'europe',
  },
  ES: {
    name: '스페인',
    nameEn: 'Spain',
    code: 'ES',
    currency: 'EUR',
    flag: '🇪🇸',
    amazon: {
      domain: 'amazon.es',
      apiEndpoint: 'https://webservices.amazon.es/paapi5/getitems',
      region: 'eu-west-1',
      marketplace: 'A1RKKUPIHCS9HS',
    },
    language: 'es-ES',
    timezone: 'Europe/Madrid',
    shippingZone: 'europe',
  },
  CA: {
    name: '캐나다',
    nameEn: 'Canada',
    code: 'CA',
    currency: 'CAD',
    flag: '🇨🇦',
    amazon: {
      domain: 'amazon.ca',
      apiEndpoint: 'https://webservices.amazon.ca/paapi5/getitems',
      region: 'us-east-1',
      marketplace: 'A2EUQ1WTGCTBG2',
    },
    language: 'en-CA',
    timezone: 'America/Toronto',
    shippingZone: 'americas',
  },
  AU: {
    name: '호주',
    nameEn: 'Australia',
    code: 'AU',
    currency: 'AUD',
    flag: '🇦🇺',
    amazon: {
      domain: 'amazon.com.au',
      apiEndpoint: 'https://webservices.amazon.com.au/paapi5/getitems',
      region: 'us-west-2',
      marketplace: 'A39IBJ37TRP1C6',
    },
    language: 'en-AU',
    timezone: 'Australia/Sydney',
    shippingZone: 'oceania',
  },
  KR: {
    name: '대한민국',
    nameEn: 'South Korea',
    code: 'KR',
    currency: 'KRW',
    flag: '🇰🇷',
    amazon: {
      domain: null, // 아마존 한국 없음
      apiEndpoint: null,
      region: null,
      marketplace: null,
    },
    language: 'ko-KR',
    timezone: 'Asia/Seoul',
    shippingZone: 'asia',
  },
};

export const KBEAUTY_CATEGORIES = {
  SKINCARE: {
    id: 'skincare',
    name: '스킨케어',
    nameEn: 'Skincare',
    icon: '🧴',
    subcategories: [
      { id: 'cleanser', name: '클렌저', nameEn: 'Cleanser' },
      { id: 'toner', name: '토너', nameEn: 'Toner' },
      { id: 'serum', name: '세럼', nameEn: 'Serum' },
      { id: 'moisturizer', name: '모이스처라이저', nameEn: 'Moisturizer' },
      { id: 'sunscreen', name: '선크림', nameEn: 'Sunscreen' },
      { id: 'mask', name: '마스크', nameEn: 'Mask' },
      { id: 'exfoliator', name: '각질제거제', nameEn: 'Exfoliator' },
    ],
  },
  MAKEUP: {
    id: 'makeup',
    name: '메이크업',
    nameEn: 'Makeup',
    icon: '💄',
    subcategories: [
      { id: 'foundation', name: '파운데이션', nameEn: 'Foundation' },
      { id: 'concealer', name: '컨실러', nameEn: 'Concealer' },
      { id: 'lipstick', name: '립스틱', nameEn: 'Lipstick' },
      { id: 'eyeshadow', name: '아이섀도', nameEn: 'Eyeshadow' },
      { id: 'mascara', name: '마스카라', nameEn: 'Mascara' },
      { id: 'eyeliner', name: '아이라이너', nameEn: 'Eyeliner' },
      { id: 'blush', name: '블러셔', nameEn: 'Blush' },
    ],
  },
  HAIRCARE: {
    id: 'haircare',
    name: '헤어케어',
    nameEn: 'Hair Care',
    icon: '💇‍♀️',
    subcategories: [
      { id: 'shampoo', name: '샴푸', nameEn: 'Shampoo' },
      { id: 'conditioner', name: '컨디셔너', nameEn: 'Conditioner' },
      { id: 'hair-mask', name: '헤어마스크', nameEn: 'Hair Mask' },
      { id: 'hair-oil', name: '헤어오일', nameEn: 'Hair Oil' },
      { id: 'styling', name: '스타일링', nameEn: 'Styling' },
    ],
  },
  BODYCARE: {
    id: 'bodycare',
    name: '바디케어',
    nameEn: 'Body Care',
    icon: '🧴',
    subcategories: [
      { id: 'body-wash', name: '바디워시', nameEn: 'Body Wash' },
      { id: 'body-lotion', name: '바디로션', nameEn: 'Body Lotion' },
      { id: 'body-scrub', name: '바디스크럽', nameEn: 'Body Scrub' },
      { id: 'hand-cream', name: '핸드크림', nameEn: 'Hand Cream' },
      { id: 'foot-care', name: '풋케어', nameEn: 'Foot Care' },
    ],
  },
  TOOLS: {
    id: 'tools',
    name: '뷰티툴',
    nameEn: 'Beauty Tools',
    icon: '🔧',
    subcategories: [
      { id: 'brushes', name: '브러쉬', nameEn: 'Brushes' },
      { id: 'sponges', name: '스펀지', nameEn: 'Sponges' },
      { id: 'devices', name: '디바이스', nameEn: 'Devices' },
      { id: 'accessories', name: '액세서리', nameEn: 'Accessories' },
    ],
  },
};

export const SHIPPING_ZONES = {
  asia: {
    name: '아시아',
    nameEn: 'Asia',
    countries: ['KR', 'JP', 'CN', 'TW', 'HK', 'SG', 'TH', 'VN', 'MY', 'ID', 'PH'],
    baseShippingCost: 15,
    deliveryTime: '7-14 days',
  },
  americas: {
    name: '아메리카',
    nameEn: 'Americas',
    countries: ['US', 'CA', 'MX', 'BR', 'AR', 'CL', 'CO', 'PE'],
    baseShippingCost: 25,
    deliveryTime: '10-21 days',
  },
  europe: {
    name: '유럽',
    nameEn: 'Europe',
    countries: ['DE', 'GB', 'FR', 'IT', 'ES', 'NL', 'BE', 'AT', 'CH', 'SE', 'NO', 'DK', 'FI'],
    baseShippingCost: 20,
    deliveryTime: '10-18 days',
  },
  oceania: {
    name: '오세아니아',
    nameEn: 'Oceania',
    countries: ['AU', 'NZ'],
    baseShippingCost: 30,
    deliveryTime: '14-28 days',
  },
};

export const POPULAR_BRANDS = [
  { name: 'The Face Shop', nameKo: '더페이스샵', logo: null },
  { name: 'Innisfree', nameKo: '이니스프리', logo: null },
  { name: 'Etude House', nameKo: '에뛰드하우스', logo: null },
  { name: 'Missha', nameKo: '미샤', logo: null },
  { name: 'Laneige', nameKo: '라네즈', logo: null },
  { name: 'Sulwhasoo', nameKo: '설화수', logo: null },
  { name: 'Amorepacific', nameKo: '아모레퍼시픽', logo: null },
  { name: 'Cosrx', nameKo: '코스알엑스', logo: null },
  { name: 'Banila Co', nameKo: '바닐라코', logo: null },
  { name: 'Tony & Tina', nameKo: '토니앤티나', logo: null },
]; 