name: Release

on:
  push:
    branches:
      - develop
    branches-ignore:
      - 'kbeauty/**'  # kbeauty 브랜치에서는 실행하지 않음

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Version packages PR
    runs-on: ubuntu-latest
    # kbeauty 관련 브랜치에서는 건너뛰기
    if: ${{ !startsWith(github.ref_name, 'kbeauty/') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
